### ISSUE TITLE
Incompatible excel sheet generated by `campbell_diagram_data.m`

### ISSUE THREAD

**Issue by mayankchetan** [OpenFAST/matlab-toolbox#10]
Hi,

I've been trying to generate the Campbell Diagram for the [IEA3.4MW](https://github.com/IEAWindTask37/IEA-3.4-130-RWT) turbine. 

The Excel files generated by `campbell_diagram_data.m` are not compatible with the `Plot_CampbellData.m` function, nor do they match the format described in `Plot_CampbellData.m`.

Should the Excel which is an input to `Plot_CampbellData.m` function be manually generated?

Thank you

**Comment by bjonkman** [comment]
Hi, @mayankchetan.

Sorry, I didn't see this issue until just now... 

The scripts for Campbell diagrams are still very much in their development stage. I've got several versions of them, and there was some lag in pull requests, so it is quite possible that they were not compatible for a while. You shouldn't have to manually generate the Excel file, but you may need to help identify the modes manually. I am finding that it is not trivial to find a method to automatically identify and match the modes across linearization cases that works for lots of turbines.

We merged updates into this toolbox today, so I would suggest trying again. I added an example script for generating Campbells: `runCampbell.m`. Take a look at it, and maybe that will help. 

I did just notice that that script is calling `CampbellMatchModeNames.m`, which is not in the OpenFAST/matlab-toolbox repo... you can replace it with the commented-out line ahead of it (`IdentifyModes.m`).

**Comment by mayankchetan** [comment]
Hi @bjonkman ,

Thank you for the update! I did look at the merge and will try running it as recommended.
