### ISSUE TITLE
blade dynamics and damage scenario simulation by stiffness reduction

### ISSUE THREAD

**Issue by ghost** [OpenFAST/matlab-toolbox#14]
Hello, I would like to simulate a damage scenario by reducing the stiffness of one of the blades in the middle of a running simulation. How feasible that is?

**Comment by bjonkman** [comment]
@yiannismatt, I think this sounds more like an OpenFAST issue than a matlab-toolbox one. I think something similar has been discussed over there already: https://github.com/OpenFAST/openfast/issues/253
