### ISSUE TITLE
CampbellMatchModeNames function missing

### ISSUE THREAD

**Issue by ramisetti** [OpenFAST/matlab-toolbox#19]
The function CampbellMatchModeNames which is called in runCampbell script is not defined. The code to this function is not committed to the repository.

**Comment by ebranlard** [comment]
You are correct, yet this function cannot be shared right now. 
You can use the following in the meantime, which is located in the Utililites folder:
```
[modeID_table, modesDesc] = IdentifyModes(CampbellData);
```
We are in the process of streamlining the Campbell diagram functionality, so hopefully we'll improve this in a couple of months.
