### ISSUE TITLE
Campbell  SubDyn and HydroDyn

### ISSUE THREAD

**Issue by sh-kim1** [OpenFAST/matlab-toolbox#32]
Hi,

https://github.com/OpenFAST/openfast/issues/480#issuecomment-663221359

I saw the above link.

Currently, can I plot the Campbell diagram by using SubDyn?

Or should I modify the source code(writeLinearizationFiles.m) to use SubDyn(or HydroDyn)

Thank you.

Best regards,

**Comment by jjonkman** [comment]
Dear @sh-kim1,

The OpenFAST issue you linked to mentioned that the linearization of OpenFAST with SubDyn enabled was under development.  This development has been completed--see: https://github.com/OpenFAST/openfast/pull/803.  The update source code is still in the review stage in the queue for merging; hopefully it will be merged into the dev and main branches of OpenFAST soon.  In the interim, you can use the code from this pull request.

Best regards,
