### ISSUE TITLE
Problems with "Matlab2FAST.m", some parameters wrong when creating the HydroDyn Input File

### ISSUE THREAD

**Issue by SYZ622** [OpenFAST/matlab-toolbox#38]
Dear openfast team,
I use the "changeFASTInputDeck.m" to extract data from HydroDyn Input File, but the new "HydroDyn. dat" generate some errors. 
The "PLATFORM ADDITIONAL STIFFNESS AND DAMPING" in old input files  is shown below:
---------------------- PLATFORM ADDITIONAL STIFFNESS AND DAMPING  -------------- [unused with PotMod=0 or 2]
             0   AddF0    - Additional preload (N, N-m) [If NBodyMod=1, one size 6*NBody x 1 vector; if NBodyMod>1, NBody size 6 x 1 vectors]
             0
             0
             0
             0
             0
             0             0             0             0             0             0   AddCLin  - Additional linear stiffness (N/m, N/rad, N-m/m, N-m/rad)                     [If NBodyMod=1, one size 6*NBody x 6*NBody matrix; if NBodyMod>1, NBody size 6 x 6 matrices]
             0             0             0             0             0             0
             0             0             0             0             0             0
             0             0             0             0             0             0
             0             0             0             0             0             0
             0             0             0             0             0             0
             0             0             0             0             0             0   AddBLin  - Additional linear damping(N/(m/s), N/(rad/s), N-m/(m/s), N-m/(rad/s))        [If NBodyMod=1, one size 6*NBody x 6*NBody matrix; if NBodyMod>1, NBody size 6 x 6 matrices]
             0             0             0             0             0             0
             0             0             0             0             0             0
             0             0             0             0             0             0
             0             0             0             0             0             0
             0             0             0             0             0             0
             0             0             0             0             0             0   AddBQuad - Additional quadratic drag(N/(m/s)^2, N/(rad/s)^2, N-m(m/s)^2, N-m/(rad/s)^2) [If NBodyMod=1, one size 6*NBody x 6*NBody matrix; if NBodyMod>1, NBody size 6 x 6 matrices]
             0             0             0             0             0             0
             0             0             0             0             0             0
             0             0             0             0             0             0
             0             0             0             0             0             0
             0             0             0             0             0             0

!!!!!however, the new input files that generated through "Matlab2FAST.m" is shown below(PLATFORM ADDITIONAL STIFFNESS AND DAMPING part, too):
---------------------- PLATFORM ADDITIONAL STIFFNESS AND DAMPING  -------------- [unused with PotMod=0 or 2]
          0   AddF0    - Additional preload (N, N-m) [If NBodyMod=1, one size 6*NBody x 1 vector; if NBodyMod>1, NBody size 6 x 1 vectors]
          0,          0,          0,          0,          0,          0    AddCLin  - Additional linear stiffness (N/m, N/rad, N-m/m, N-m/rad)                     [If NBodyMod=1, one size 6*NBody x 6*NBody matrix; if NBodyMod>1, NBody size 6 x 6 matrices]
          0,          0,          0,          0,          0,          0    AddBLin  - Additional linear damping(N/(m/s), N/(rad/s), N-m/(m/s), N-m/(rad/s))        [If NBodyMod=1, one size 6*NBody x 6*NBody matrix; if NBodyMod>1, NBody size 6 x 6 matrices]
          0,          0,          0,          0,          0,          0    AddBQuad - Additional quadratic drag(N/(m/s)^2, N/(rad/s)^2, N-m(m/s)^2, N-m/(rad/s)^2) [If NBodyMod=1, one size 6*NBody x 6*NBody matrix; if NBodyMod>1, NBody size 6 x 6 matrices]

Some of the following parameters are also different, I'm not sure if it's my setup or the program. Any suggestions/guidance? Thank you!!!

**Comment by bjonkman** [comment]
This toolbox is a little ahead of the OpenFAST main and dev branches. We (I) updated it to convert files for testing a current OpenFAST pull request (slated to be part of OpenFAST v4.0.0): https://github.com/OpenFAST/openfast/pull/1008

You can go back a commit or two, before #37 was merged into this toolbox, and see if that works.

**Comment by SYZ622** [comment]
> This toolbox is a little ahead of the OpenFAST main and dev branches. We (I) updated it to convert files for testing a current OpenFAST pull request (slated to be part of OpenFAST v4.0.0): [OpenFAST/openfast#1008](https://github.com/OpenFAST/openfast/pull/1008)
> 
> You can go back a commit or two, before #37 was merged into this toolbox, and see if that works.

Thanks for your reply！！！I didn't find the solution before #37, but I solve this problem by another way.
Best regards
