### ISSUE TITLE
Couldnot locate openfast3.0_x64s.exe in matlab-toolbox-main folder

### ISSUE THREAD

**Issue by MuhammadSharjil** [OpenFAST/matlab-toolbox#41]
Hello
I am trying to execute the mfile scripts but getting the errors 'could not locate openfast3.0_x64s.exe in _ExampleData folder'.
I tried locating the file but there is no such file.
It will be great to get a response.
Thanks

**Comment by ebranlard** [comment]
Hi,

We do not provide binaries of OpenFAST as part of this repository as it would make the repository too big. 
You'll need to adapt the script to point to an openfast executable  that you have on your machine. 
You can download them from the openfast repository: https://github.com/OpenFAST/openfast/releases

Please note that the OpenFAST input files change from one OpenFAST version to the next, so you might run into issues with your OpenFAST executable not matching with the example inputs of this repository. We try to keep the input files in this repository up to date with the latest version of OpenFAST, but we sometimes miss some. 

I hope that helps
Emmanuel
