### ISSUE TITLE
getPSD.m

### ISSUE THREAD

**Issue by lk73438702** [OpenFAST/matlab-toolbox#43]
how use getPSD.m

**Comment by jjonkman** [comment]
Dear @lk73438702,

There are comments at the top of the script to guide you in its use: https://github.com/OpenFAST/matlab-toolbox/blob/main/Utilities/getPSD.m.

Best regards,

**Comment by lk73438702** [comment]
Dear @https://github.com/jjonkman
Since it is the first time for me to use matlab and openfast, Do you have relevant videos of specific cases using getFPS.m?


Best regards,

**Comment by jjonkman** [comment]
Dear @lk73438702,

I'm not aware of any tutorial videos on how to run _getPSD.m_.  This is not a place to ask questions on general usage of MATLAB.  I would search MATLAB help for that.

Best regards,
