### ISSUE TITLE
upload output file to matlab

### ISSUE THREAD

**Issue by falascao** [OpenFAST/matlab-toolbox#44]
Dear openfast team,
i wanted to ask you what's the procedure to upload the output file generated from the openfast simulation in Matlab.
Thank you

**Comment by jjonkman** [comment]
Dear @falascao,

See MATLAB Toolbox functions _ReadFASTtext.m_ for ASCII-formmated OpenFAST output files or _ReadFASTbinary.m_ for binary-formatted OpenFAST output files: https://github.com/OpenFAST/matlab-toolbox/tree/main/Utilities.

Best regards,

**Comment by falascao** [comment]
Dear @jjonkman,
i had download the matlab toolbox folder and i set his path in Matlab; but when i try to open openfast's files like .out and .outb, Matlab open the file in text mode. Doing that, the matlab's workspace is empty and don't load the data.

Best regards and thank you for your help.

**Comment by jjonkman** [comment]
Dear @falascao,

I'm not sure what you mean when you say:

> but when i try to open openfast's files like .out and .outb, Matlab open the file in text mode. 

Can you clarify or share a screenshot of the issue?

Best regards,

**Comment by falascao** [comment]
Dear @jjonkman,
this is the screenshot

![WhatsApp Image 2023-10-12 at 17 08 36](https://github.com/OpenFAST/matlab-toolbox/assets/146757474/eb240b41-82ea-452e-9a51-cd752f3c3f54)
68)
![WhatsApp Image 2023-10-12 at 16 55 39](https://github.com/OpenFAST/matlab-toolbox/assets/146757474/004fb722-e879-418c-8a16-215ca18e528a)
![WhatsApp Image 2023-10-12 at 16 57 13](https://github.com/OpenFAST/matlab-toolbox/assets/146757474/c6fa0a8b-4c73-40ab-a276-b67f88207a2a)
![WhatsApp Image 2023-10-12 at 16 55 19](https://github.com/OpenFAST/matlab-toolbox/assets/146757474/066553ae-ffcb-4732-93a5-14743c6b5a90)

**Comment by bjonkman** [comment]
To read the files, you need to use the functions Jason mentioned. For example, to read the binary .outb file, you call 
`[Channels, ChannelNames, ChannelUnits] = ReadFASTbinary('5MW_OC4Semi_Linear.outb')`
from the Matlab command window, and the data from the file will be stored in the function's output variables.

**Comment by falascao** [comment]
Everything works perfectly. Thank you so much for your support.
Best regards
